on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/ytsaurus/ytsaurus-ui.git"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: "true"
        github_token: ${{ secrets.GITHUB_TOKEN }}
